import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { verifySession } from "./auth/session";
// import WebSocket from "./component/webSocket";
import WebsocketProvider from "./socket";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const {token} = await verifySession();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <WebsocketProvider token={token}>
          {children}
        </WebsocketProvider>
      </body>
    </html>
  );
}
